import { useState, useEffect } from "react";
import AuthScreen from "./AuthScreen";
import StarterQuiz from "./StarterQuiz";
import DungeonGame from "./DungeonGame";
import VillageGame from "./VillageGame";
import { getProfile, getTeam, resetProfile } from "../lib/auth";
import { supabase } from "../lib/supabase";
import { useIsMobile } from "../lib/useIsMobile";
import { getLanguage, subscribe } from "../stores/language";
import { t } from "../stores/translations";

export default function Dungeon() {
  const [account, setAccount] = useState(null);
  const [profile, setProfile] = useState(null);
  const [team, setTeam] = useState([]);
  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState(null);
  const [inDungeon, setInDungeon] = useState(false);
  const [language, setLanguage] = useState(getLanguage());
  const isMobile = useIsMobile();

  useEffect(() => subscribe(setLanguage), []);

  // Restore session from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem("pokevisa_account");
      if (saved) {
        const acc = JSON.parse(saved);
        setAccount(acc);
        loadAccountData(acc.id);
      } else {
        setLoading(false);
      }
    } catch {
      setLoading(false);
    }
  }, []);

  async function loadAccountData(accountId) {
    setLoading(true);
    try {
      const [prof, tm] = await Promise.all([getProfile(accountId), getTeam(accountId)]);
      // Only reset the profile when the starter creation failed mid-way and the
      // account has nothing to lose. A player with camp/stored Pokémon is never
      // reset even if their active team is temporarily empty.
      if (tm.length === 0 && prof && prof.starter_id && (prof.stored_pokemon || []).length === 0) {
        await resetProfile(accountId);
        setProfile(null);
      } else {
        setProfile(prof);
      }
      setTeam(tm);
    } catch (err) {
      console.error("Failed to load account data:", err);
    } finally {
      setLoading(false);
    }
  }

  function handleAuth(acc) {
    setAccount(acc);
    localStorage.setItem("pokevisa_account", JSON.stringify(acc));
    loadAccountData(acc.id);
  }

  function handleLogout() {
    setAccount(null);
    setProfile(null);
    setTeam([]);
    setSession(null);
    setInDungeon(false);
    localStorage.removeItem("pokevisa_account");
  }

  function handleQuizComplete() {
    loadAccountData(account.id);
  }

  function handleJoin(roomInfo) {
    setSession(roomInfo);
    setInDungeon(false);
  }

  async function handleStartDungeon() {
    if (!session) return;

    // Dungeon rooms are already created in "playing" status by the three
    // adventure modes (solo / invade / play-with-a-friend). dungeon_state is
    // generated by DungeonGame on entry with valid columns only.
    setInDungeon(true);
  }

  async function handleDungeonEnd() {
    if (!session) { setInDungeon(false); return; }

    if (session.isHost) {
      // The host owns the room — leaving closes the dungeon for everyone.
      await supabase
        .from("room_players")
        .delete()
        .eq("room_id", session.roomId);

      await supabase
        .from("rooms")
        .update({ status: "lobby" })
        .eq("id", session.roomId);

      await supabase
        .from("dungeon_state")
        .delete()
        .eq("room_id", session.roomId);
    } else {
      // Non-hosts (coop friends / invaders) only remove their own row so the
      // host's dungeon keeps running for the others.
      await supabase
        .from("room_players")
        .delete()
        .eq("room_id", session.roomId)
        .eq("player_id", session.playerId);
    }

    // Clear the session so VillageGame's auto-join puts the player back into a
    // fresh village lobby (the dungeon room is now empty of them).
    setInDungeon(false);
    setSession(null);
    loadAccountData(account.id);
  }

  function handleDungeonTeamUpdate() {
    loadAccountData(account.id);
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900">
        <p className="text-sm text-slate-400">...</p>
      </div>
    );
  }

  // The dungeon/village flow uses a fixed 32px tile grid and isn't playable on
  // small screens yet, so mobile users only get a notice + a way back home.
  // The rest of the flow (auth, village, dungeon) is never mounted.
  if (isMobile) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-6 bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900 px-4 text-center">
        <span className="text-5xl">📱</span>
        <h1 className="text-2xl font-bold text-slate-100">{t("Dungeon Crawler", language)}</h1>
        <p className="max-w-sm text-sm text-amber-400 bg-amber-500/10 border border-amber-500/30 rounded-2xl px-6 py-4">
          {t("dungeon-mobile-warning", language)}
        </p>
        <a
          href="/"
          className="rounded-xl bg-slate-700 px-6 py-3 text-sm font-semibold text-white hover:bg-slate-600 transition-colors"
        >
          {t("Back to Pokédex", language)}
        </a>
      </div>
    );
  }

  if (!account) {
    return <AuthScreen onAuth={handleAuth} />;
  }

  if (!profile || !profile.starter_id) {
    return <StarterQuiz accountId={account.id} onComplete={handleQuizComplete} />;
  }

  if (session && inDungeon) {
    return (
      <DungeonGame
        roomId={session.roomId}
        roomCode={session.roomCode}
        playerId={session.playerId}
        isHost={session.isHost}
        accountId={account.id}
        accountName={account.display_name}
        team={team}
        onTeamUpdate={handleDungeonTeamUpdate}
        onLeave={handleDungeonEnd}
      />
    );
  }

  return (
    <VillageGame
      session={session}
      accountId={account.id}
      accountName={account.display_name}
      team={team}
      onTeamUpdate={handleDungeonTeamUpdate}
      onJoin={handleJoin}
      onStartDungeon={handleStartDungeon}
      onLogout={handleLogout}
    />
  );
}
